site_name: "READDI-AC Data Management Guide"
theme:
  name: material
  palette:
    scheme: default
    primary: light blue
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Site Description: index.md
  - READDI-AC Data Stewardship: datastewardship.md
  - Understanding CDD Vault: cddvault.md
  - Data Upload Guide: data-upload_guide.md
  - FAQ: FAQ.md
  - Contact Us: contact_us.md

extra_css:
  - custom.css

site_url: https://avarga24.github.io/datamgmtguide_READDI-AC/
repo_url: https://github.com/avarga24/datamgmtguide_READDI-AC
