site_name: "FRINK Landing zone"
theme:
  name: material
  palette:
    scheme: default
    primary: light blue
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Upload Guide: index.md
  - KG Status: kg-status.md
site_url: https://frink-okn.github.io/frink-landing-zone/
repo_url: https://github.com/frink-okn/frink-landing-zone/
