site_name: "FRINK Landing zone"
theme:
  name: material
  palette:
    scheme: default
    primary: light blue
plugins:
  - search
nav:
  - Overview: index.md
site_url: https://frink-okn.github.io/frink-landing-zone/
repo_url: https://github.com/frink-okn/frink-landing-zone/