name: Deploy MkDocs

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:  # Ensure steps are indented correctly under the job
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build the site and list directory
        run: |
          mkdocs build
          ls -la  # Lists the contents of the current directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: github-pages
